### ISSUE TITLE
Update Package interface

### ISSUE THREAD

**Issue by georgiana-b** [frictionlessdata/datapackage-rb#32]
The `Package` class should be brought in line with v1 [proposed functionality](https://github.com/frictionlessdata/implementations#datapackage): 
 
- [x] refactor how [`dead_resources` are handled](https://github.com/frictionlessdata/datapackage-rb/blob/master/lib/datapackage/package.rb#L103-L107).
- [x] add `add_resource` method to add a `Resource` to the datapackage
- [x] add `remove_resource` method to remove a `Resource`
- [x] rename `load_resource` to `get_resource` 
- [x] add method to `save` the changes
- [ ] figure out what `update()` method [here](https://github.com/frictionlessdata/implementations#datapackage) should be

**Comment by roll** [comment]
Should it be a `DataPackage` class?
