### ISSUE TITLE
Update jsonschemas to specs-v1

### ISSUE THREAD

**Issue by georgiana-b** [frictionlessdata/datapackage-rb#34]
The source used to [cache the schemas](https://github.com/frictionlessdata/datapackage-rb#updating-the-local-schemas-cache) has been deprecated and should be replaced with https://github.com/frictionlessdata/specs/tree/master/sources.

---

# Overview

Across libraries I use simple approach to sync with specs - https://github.com/frictionlessdata/tableschema-py/blob/master/Makefile#L16-L17. So you could:

- add something like this (also you could add test to check jsonschema is not out-of-date)
- then update jsonschema
- and fix all stuff which is not compatible with specs v1

**Comment by roll** [comment]
@georgiana-b 
Alsmost everything you need to finish this one is in https://github.com/frictionlessdata/datapackage-js/pull/76
