### ISSUE TITLE
Add support for schema, dialect dereferencing

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-rb#38]
# Overview

See - http://specs.frictionlessdata.io/implementation/#on-dereferencing-and-descriptor-validation

# Tasks

- [ ] port this functions - https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/helpers.py#L72-L135 (skip JSON pointer support for now!)
- [ ] re-use it in `DataPackage`, `Resource` and `validate` to dereference descriptor (see Py/Js implementation)

**Comment by georgiana-b** [comment]
@roll  Looks like the Python version of [resource dereferencing](https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/helpers.py#L96) considers a JSON pointer only something that starts with `#` so only a pointer to a section of the same file. 
But there can be JSON pointers to another file like `https://specs.frictionlessdata.io/schemas/data-package.json#properties` a.k.a [JSON references](https://json-spec.readthedocs.io/reference.html). You are suggesting we shouldn't support these external pointers (JSON references)?

Also, I'm not convinced that `starts_with('#')` is the correct way to identify a JSON pointer. Although TBH I don't understand what [the standard requires](https://tools.ietf.org/html/rfc6901), it seems that in practice a pointer is the value of the key `$ref` (see the first example [here](https://json-spec.readthedocs.io/pointer.html)).

From the [dereferencing specs](http://specs.frictionlessdata.io/implementation/#on-dereferencing-and-descriptor-validation) I understand that a reference can only be `a URL or a POSIX path` but if you think we should support JSON references don't you think we should stick to the standard and rely of `$ref` key?

**Comment by roll** [comment]
@georgiana-b :smiley: 
> port this functions - https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/helpers.py#L72-L135 **(skip JSON pointer support for now!)**

It seems JSON Pointers will not be a part of final specs v1 release.

**Comment by georgiana-b** [comment]
I completely missed the `skip JSON pointer support part` :woman_facepalming:. There goes a day of work...At least I know a lot about JSON references now lol.
Thanks for the help!

I'll push the current code that supports JSON pointers to a branch just in case they get included in specs later.

**Comment by georgiana-b** [comment]
Code that supports dereferencing JSON references has been pushed to  [feature/dereferencing-JSON-pointers](https://github.com/frictionlessdata/datapackage-rb/tree/feature/dereferencing-JSON-pointers). Main dereferencing logic can be found in [Helpers module](https://github.com/frictionlessdata/datapackage-rb/blob/feature/dereferencing-JSON-pointers/lib/datapackage/helpers.rb).
