### ISSUE TITLE
Fix development and tests for Ruby 2.4

### ISSUE THREAD

**Issue by georgiana-b** [frictionlessdata/datapackage-rb#42]
Currently `datapackage` raises an error when installed on Ruby 2.4.1.

**Comment by georgiana-b** [comment]
This depends on the new FakeWeb release which, according to  chrisk/fakeweb#57 is coming soon.

**Comment by pmackay** [comment]
There hasnt yet been a new release of fakeweb. What do others think about migrating to use webmock instead, which has more regular support?

**Comment by switzersc** [comment]
Hey y'all! User of the gem here and in the process of installing it locally to develop on it (at which point I ran into this issue). Just want to +1 the suggestion to move to webmock. =]

**Comment by roll** [comment]
Merging into https://github.com/frictionlessdata/datapackage-rb/issues/53
