### ISSUE TITLE
Issue with `describe DataPackage::Interpreter` on Travis

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-rb#55]
# Overview

@switzersc 
Something wrong happened to Travis and our tests were disabled. Could you please take a look at this failing build - https://travis-ci.org/frictionlessdata/datapackage-rb/jobs/613575560

**Comment by switzersc-usds** [comment]
Yeah, I'll take a look tonight!

**Comment by roll** [comment]
Thanks a lot!
